<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>RemoteCommerce</RootNamespace>
    <AssemblyName>RemoteCommerce</AssemblyName>
    <InvariantGlobalization>false</InvariantGlobalization>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <WarningsAsErrors>$(WarningsAsErrors);1591</WarningsAsErrors>
    <UserSecretsId>d8af9ac6-fb8e-45f1-a333-335d35f243dd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="MudBlazor" />
    <ProjectReference Include="../RemoteCommerce.Abstractions/RemoteCommerce.Abstractions.csproj" />
    <ProjectReference Include="../RemoteCommerce.Plugin.Abstractions/RemoteCommerce.Plugin.Abstractions.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <Target Name="AddMigration">
    <PropertyGroup>
      <MigrationName>$(Name)</MigrationName>
    </PropertyGroup>

    <Error Condition="'$(MigrationName)' == ''" Text="Missing migration name. Example: dotnet build -t:AddMigration &quot;-p:Name=MyMigration&quot;" />

    <Exec Command="dotnet ef migrations add $(MigrationName) --output-dir Infrastructure\Persistence\Migrations" />
  </Target>
</Project>
