namespace RemoteCommerce.Infrastructure.Catalog;

/// <summary>Provides EF Core persistence for the RemoteCommerce catalog.</summary>
public sealed class CatalogService(IDbContextFactory<CommerceDbContext> dbFactory) : ICatalogService
{
    /// <inheritdoc />
    public async Task<ProductModel> CreateProductAsync(CreateProductCommand command, CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var product = new Product { Name = command.Name.Trim(), Slug = command.Slug, Sku = command.Sku, ShortDescription = command.ShortDescription, Description = command.Description, Status = command.Status, ProductType = command.ProductType, Price = command.Price, CompareAtPrice = command.CompareAtPrice, Currency = command.Currency.ToUpperInvariant(), BrandId = command.BrandId }; db.Products.Add(product); await db.SaveChangesAsync(cancellationToken); return Map(product); }
    /// <inheritdoc />
    public async Task<ProductModel?> UpdateProductAsync(UpdateProductCommand command, CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var product = await db.Products.SingleOrDefaultAsync(x => x.Id == command.Id, cancellationToken); if (product is null) return null; product.Name = command.Name.Trim(); product.Slug = command.Slug; product.Sku = command.Sku; product.ShortDescription = command.ShortDescription; product.Description = command.Description; product.Status = command.Status; product.ProductType = command.ProductType; product.Price = command.Price; product.CompareAtPrice = command.CompareAtPrice; product.Currency = command.Currency.ToUpperInvariant(); product.BrandId = command.BrandId; product.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(cancellationToken); return Map(product); }
    /// <inheritdoc />
    public async Task DeleteProductAsync(Guid id, CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var product = await db.Products.SingleOrDefaultAsync(x => x.Id == id, cancellationToken); if (product is null) return; db.Products.Remove(product); await db.SaveChangesAsync(cancellationToken); }
    /// <inheritdoc />
    public async Task<ProductModel?> GetProductAsync(Guid id, CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var product = await db.Products.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, cancellationToken); return product is null ? null : Map(product); }
    /// <inheritdoc />
    public async Task<PagedResult<ProductModel>> ListProductsAsync(ProductListQuery query, CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var page = Math.Max(1, query.Page); var pageSize = Math.Clamp(query.PageSize, 1, 100); IQueryable<Product> products = db.Products.AsNoTracking(); if (!string.IsNullOrWhiteSpace(query.Search)) products = products.Where(x => x.Name.Contains(query.Search) || x.Description.Contains(query.Search)); if (query.Status.HasValue) products = products.Where(x => x.Status == query.Status.Value); if (query.BrandId.HasValue) products = products.Where(x => x.BrandId == query.BrandId.Value); if (!string.IsNullOrWhiteSpace(query.Sku)) products = products.Where(x => x.Sku == query.Sku); if (query.ProductType.HasValue) products = products.Where(x => x.ProductType == query.ProductType.Value); if (query.CategoryId.HasValue) products = products.Where(x => x.Categories.Any(c => c.CategoryId == query.CategoryId.Value)); if (!string.IsNullOrWhiteSpace(query.Tag)) products = products.Where(x => x.Tags.Any(t => t.Tag.Name == query.Tag)); var total = await products.CountAsync(cancellationToken); var items = await products.OrderByDescending(x => x.CreatedAt).Skip((page - 1) * pageSize).Take(pageSize).Select(x => new ProductModel(x.Id, x.Name, x.Slug, x.Sku, x.ShortDescription, x.Description, x.Status, x.ProductType, x.Price, x.CompareAtPrice, x.Currency, x.BrandId, x.CreatedAt, x.UpdatedAt)).ToListAsync(cancellationToken); return new PagedResult<ProductModel>(items, page, pageSize, total); }
    /// <inheritdoc />
    public async Task<IReadOnlyList<CategoryModel>> GetCategoriesAsync(CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); return await db.Categories.AsNoTracking().OrderBy(x => x.DisplayOrder).ThenBy(x => x.Name).Select(x => new CategoryModel(x.Id, x.Name, x.Slug, x.Description, x.ParentId, x.DisplayOrder)).ToListAsync(cancellationToken); }
    /// <inheritdoc />
    public async Task<IReadOnlyList<BrandModel>> GetBrandsAsync(CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); return await db.Brands.AsNoTracking().OrderBy(x => x.Name).Select(x => new BrandModel(x.Id, x.Name, x.Slug, x.Description, x.LogoMediaId)).ToListAsync(cancellationToken); }
    /// <inheritdoc />
    public async Task<IReadOnlyList<TagModel>> GetTagsAsync(CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); return await db.Tags.AsNoTracking().OrderBy(x => x.Name).Select(x => new TagModel(x.Id, x.Name, x.Slug, x.Description)).ToListAsync(cancellationToken); }
    /// <inheritdoc />
    public async Task<IReadOnlyList<AttributeModel>> GetAttributesAsync(CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); return await db.ProductAttributes.AsNoTracking().Include(x => x.Values).OrderBy(x => x.Name).Select(x => new AttributeModel(x.Id, x.Name, x.Slug, x.Values.OrderBy(v => v.Value).Select(v => new AttributeValueModel(v.Id, v.Value, v.Slug)).ToList())).ToListAsync(cancellationToken); }
    /// <inheritdoc />
    public async Task<CategoryModel> CreateCategoryAsync(CreateCategoryCommand command, CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); if (command.ParentId.HasValue && !await db.Categories.AnyAsync(x => x.Id == command.ParentId.Value, cancellationToken)) throw new ValidationException("The parent category does not exist."); var category = new Category { Name = command.Name.Trim(), Slug = command.Slug, Description = command.Description, ParentId = command.ParentId, DisplayOrder = command.DisplayOrder }; db.Categories.Add(category); await db.SaveChangesAsync(cancellationToken); return new CategoryModel(category.Id, category.Name, category.Slug, category.Description, category.ParentId, category.DisplayOrder); }
    /// <inheritdoc />
    public async Task<BrandModel> CreateBrandAsync(CreateBrandCommand command, CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var brand = new Brand { Name = command.Name.Trim(), Slug = command.Slug, Description = command.Description, LogoMediaId = command.LogoMediaId }; db.Brands.Add(brand); await db.SaveChangesAsync(cancellationToken); return new BrandModel(brand.Id, brand.Name, brand.Slug, brand.Description, brand.LogoMediaId); }
    /// <inheritdoc />
    public async Task<TagModel> CreateTagAsync(CreateTagCommand command, CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var tag = new Tag { Name = command.Name.Trim(), Slug = command.Slug, Description = command.Description }; db.Tags.Add(tag); await db.SaveChangesAsync(cancellationToken); return new TagModel(tag.Id, tag.Name, tag.Slug, tag.Description); }
    private static ProductModel Map(Product product) => new(product.Id, product.Name, product.Slug, product.Sku, product.ShortDescription, product.Description, product.Status, product.ProductType, product.Price, product.CompareAtPrice, product.Currency, product.BrandId, product.CreatedAt, product.UpdatedAt);
}
