namespace RemoteCommerce.Infrastructure.Catalog;

/// <summary>Provides EF Core persistence for the RemoteCommerce catalog.</summary>
public sealed class CatalogService(IDbContextFactory<CommerceDbContext> dbFactory) : ICatalogService
{
    /// <inheritdoc />
    public async Task<ProductModel> CreateProductAsync(CreateProductCommand command, CancellationToken cancellationToken)
    {
        await using var db = await dbFactory.CreateDbContextAsync(cancellationToken);
        await EnsureUniqueProductAsync(db, command.Slug, command.Sku, null, cancellationToken);
        var product = new Product { Name = command.Name.Trim(), Slug = command.Slug, Sku = command.Sku, ShortDescription = command.ShortDescription, Description = command.Description, Status = command.Status, ProductType = command.ProductType, Price = command.Price, CompareAtPrice = command.CompareAtPrice, Currency = command.Currency.ToUpperInvariant(), BrandId = command.BrandId };
        db.Products.Add(product); await db.SaveChangesAsync(cancellationToken); return Map(product);
    }
    /// <inheritdoc />
    public async Task<ProductModel?> UpdateProductAsync(UpdateProductCommand command, CancellationToken cancellationToken)
    {
        await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var product = await db.Products.SingleOrDefaultAsync(x => x.Id == command.Id, cancellationToken); if (product is null) return null;
        await EnsureUniqueProductAsync(db, command.Slug, command.Sku, command.Id, cancellationToken); Apply(product, command); await db.SaveChangesAsync(cancellationToken); return Map(product);
    }
    /// <inheritdoc />
    public async Task DeleteProductAsync(Guid id, CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var product = await db.Products.SingleOrDefaultAsync(x => x.Id == id, cancellationToken); if (product is not null) { db.Products.Remove(product); await db.SaveChangesAsync(cancellationToken); } }
    /// <inheritdoc />
    public async Task<ProductModel?> GetProductAsync(Guid id, CancellationToken cancellationToken) { await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var product = await db.Products.AsNoTracking().SingleOrDefaultAsync(x => x.Id == id, cancellationToken); return product is null ? null : Map(product); }
    /// <inheritdoc />
    public async Task<PagedResult<ProductModel>> ListProductsAsync(ProductListQuery query, CancellationToken cancellationToken)
    {
        await using var db = await dbFactory.CreateDbContextAsync(cancellationToken); var page = Math.Max(1, query.Page); var pageSize = Math.Clamp(query.PageSize, 1, 100); IQueryable<Product> products = db.Products.AsNoTracking();
        if (!string.IsNullOrWhiteSpace(query.Search)) products = products.Where(x => x.Name.Contains(query.Search) || x.Description.Contains(query.Search));
        if (query.Status.HasValue) products = products.Where(x => x.Status == query.Status.Value);
        if (query.BrandId.HasValue) products = products.Where(x => x.BrandId == query.BrandId.Value);
        if (!string.IsNullOrWhiteSpace(query.Sku)) products = products.Where(x => x.Sku == query.Sku);
        if (query.ProductType.HasValue) products = products.Where(x => x.ProductType == query.ProductType.Value);
        if (query.CategoryId.HasValue) products = products.Where(x => x.Categories.Any(c => c.CategoryId == query.CategoryId.Value));
        if (!string.IsNullOrWhiteSpace(query.Tag)) products = products.Where(x => x.Tags.Any(t => t.Tag!.Slug == query.Tag || t.Tag!.Name == query.Tag));
        var total = await products.CountAsync(cancellationToken); var items = await products.OrderByDescending(x => x.CreatedAt).Skip((page - 1) * pageSize).Take(pageSize).Select(x => new ProductModel(x.Id, x.Name, x.Slug, x.Sku, x.ShortDescription, x.Description, x.Status, x.ProductType, x.Price, x.CompareAtPrice, x.Currency, x.BrandId, x.CreatedAt, x.UpdatedAt)).ToListAsync(cancellationToken); return new(items, page, pageSize, total);
    }
    /// <inheritdoc /> public async Task<IReadOnlyList<CategoryModel>> GetCategoriesAsync(CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); return await db.Categories.AsNoTracking().OrderBy(x => x.DisplayOrder).ThenBy(x => x.Name).Select(x => new CategoryModel(x.Id, x.Name, x.Slug, x.Description, x.ParentId, x.DisplayOrder)).ToListAsync(c); }
    /// <inheritdoc /> public async Task<IReadOnlyList<BrandModel>> GetBrandsAsync(CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); return await db.Brands.AsNoTracking().OrderBy(x => x.Name).Select(x => new BrandModel(x.Id, x.Name, x.Slug, x.Description, x.LogoMediaId)).ToListAsync(c); }
    /// <inheritdoc /> public async Task<IReadOnlyList<TagModel>> GetTagsAsync(CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); return await db.Tags.AsNoTracking().OrderBy(x => x.Name).Select(x => new TagModel(x.Id, x.Name, x.Slug, x.Description)).ToListAsync(c); }
    /// <inheritdoc /> public async Task<IReadOnlyList<AttributeModel>> GetAttributesAsync(CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); return await db.ProductAttributes.AsNoTracking().Include(x => x.Values).OrderBy(x => x.Name).Select(x => new AttributeModel(x.Id, x.Name, x.Slug, x.Values.OrderBy(v => v.Value).Select(v => new AttributeValueModel(v.Id, v.Value, v.Slug)).ToList())).ToListAsync(c); }
    /// <inheritdoc /> public async Task<CategoryModel> CreateCategoryAsync(CreateCategoryCommand command, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); await ValidateParentAsync(db, command.ParentId, null, c); var category = new Category { Name = command.Name.Trim(), Slug = command.Slug, Description = command.Description, ParentId = command.ParentId, DisplayOrder = command.DisplayOrder }; db.Categories.Add(category); await db.SaveChangesAsync(c); return Map(category); }
    /// <inheritdoc /> public async Task<CategoryModel?> UpdateCategoryAsync(UpdateCategoryCommand command, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var category = await db.Categories.SingleOrDefaultAsync(x => x.Id == command.Id, c); if (category is null) return null; await ValidateParentAsync(db, command.ParentId, command.Id, c); category.Name = command.Name.Trim(); category.Slug = command.Slug; category.Description = command.Description; category.ParentId = command.ParentId; category.DisplayOrder = command.DisplayOrder; category.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(c); return Map(category); }
    /// <inheritdoc /> public async Task DeleteCategoryAsync(Guid id, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var entity = await db.Categories.SingleOrDefaultAsync(x => x.Id == id, c); if (entity is not null) { db.Categories.Remove(entity); await db.SaveChangesAsync(c); } }
    /// <inheritdoc /> public async Task<BrandModel> CreateBrandAsync(CreateBrandCommand command, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var entity = new Brand { Name = command.Name.Trim(), Slug = command.Slug, Description = command.Description, LogoMediaId = command.LogoMediaId }; db.Brands.Add(entity); await db.SaveChangesAsync(c); return Map(entity); }
    /// <inheritdoc /> public async Task<BrandModel?> UpdateBrandAsync(UpdateBrandCommand command, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var entity = await db.Brands.SingleOrDefaultAsync(x => x.Id == command.Id, c); if (entity is null) return null; entity.Name = command.Name.Trim(); entity.Slug = command.Slug; entity.Description = command.Description; entity.LogoMediaId = command.LogoMediaId; entity.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(c); return Map(entity); }
    /// <inheritdoc /> public async Task DeleteBrandAsync(Guid id, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var entity = await db.Brands.SingleOrDefaultAsync(x => x.Id == id, c); if (entity is not null) { db.Brands.Remove(entity); await db.SaveChangesAsync(c); } }
    /// <inheritdoc /> public async Task<TagModel> CreateTagAsync(CreateTagCommand command, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var entity = new Tag { Name = command.Name.Trim(), Slug = command.Slug, Description = command.Description }; db.Tags.Add(entity); await db.SaveChangesAsync(c); return Map(entity); }
    /// <inheritdoc /> public async Task<TagModel?> UpdateTagAsync(UpdateTagCommand command, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var entity = await db.Tags.SingleOrDefaultAsync(x => x.Id == command.Id, c); if (entity is null) return null; entity.Name = command.Name.Trim(); entity.Slug = command.Slug; entity.Description = command.Description; entity.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(c); return Map(entity); }
    /// <inheritdoc /> public async Task DeleteTagAsync(Guid id, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var entity = await db.Tags.SingleOrDefaultAsync(x => x.Id == id, c); if (entity is not null) { db.Tags.Remove(entity); await db.SaveChangesAsync(c); } }
    /// <inheritdoc /> public async Task<ProductVariantModel> CreateVariantAsync(CreateProductVariantCommand command, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); if (!await db.Products.AnyAsync(x => x.Id == command.ProductId, c)) throw new ValidationException("The product does not exist."); if (await db.ProductVariants.AnyAsync(x => x.Sku == command.Sku, c)) throw new ValidationException("The variant SKU is already in use."); var v = new ProductVariant { ProductId = command.ProductId, Sku = command.Sku, Price = command.Price, CompareAtPrice = command.CompareAtPrice, StockQuantity = command.StockQuantity, ManageStock = command.ManageStock, Status = command.Status }; db.ProductVariants.Add(v); await db.SaveChangesAsync(c); return Map(v); }
    /// <inheritdoc /> public async Task<ProductVariantModel?> UpdateVariantAsync(UpdateProductVariantCommand command, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var v = await db.ProductVariants.SingleOrDefaultAsync(x => x.Id == command.Id && x.ProductId == command.ProductId, c); if (v is null) return null; if (await db.ProductVariants.AnyAsync(x => x.Sku == command.Sku && x.Id != command.Id, c)) throw new ValidationException("The variant SKU is already in use."); v.Sku = command.Sku; v.Price = command.Price; v.CompareAtPrice = command.CompareAtPrice; v.StockQuantity = command.StockQuantity; v.ManageStock = command.ManageStock; v.Status = command.Status; v.UpdatedAt = DateTime.UtcNow; await db.SaveChangesAsync(c); return Map(v); }
    /// <inheritdoc /> public async Task DeleteVariantAsync(Guid productId, Guid variantId, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var v = await db.ProductVariants.SingleOrDefaultAsync(x => x.Id == variantId && x.ProductId == productId, c); if (v is not null) { db.ProductVariants.Remove(v); await db.SaveChangesAsync(c); } }
    /// <inheritdoc /> public async Task<IReadOnlyList<ProductVariantModel>> GetVariantsAsync(Guid productId, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); return await db.ProductVariants.AsNoTracking().Where(x => x.ProductId == productId).OrderBy(x => x.Sku).Select(x => new ProductVariantModel(x.Id, x.ProductId, x.Sku, x.Price, x.CompareAtPrice, x.StockQuantity, x.ManageStock, x.Status)).ToListAsync(c); }
    /// <inheritdoc /> public async Task<IReadOnlyList<ProductMetadataModel>> GetMetadataAsync(Guid productId, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); return await db.ProductMetadata.AsNoTracking().Where(x => x.ProductId == productId).OrderBy(x => x.Key).Select(x => new ProductMetadataModel(x.Id, x.ProductId, x.Key, x.Type, x.Value)).ToListAsync(c); }
    /// <inheritdoc /> public async Task<ProductMetadataModel> UpsertMetadataAsync(UpsertProductMetadataCommand command, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); if (!await db.Products.AnyAsync(x => x.Id == command.ProductId, c)) throw new ValidationException("The product does not exist."); var m = await db.ProductMetadata.SingleOrDefaultAsync(x => x.ProductId == command.ProductId && x.Key == command.Key, c); if (m is null) { m = new ProductMetadata { ProductId = command.ProductId, Key = command.Key, Type = command.Type, Value = command.Value }; db.ProductMetadata.Add(m); } else { m.Type = command.Type; m.Value = command.Value; m.UpdatedAt = DateTime.UtcNow; } await db.SaveChangesAsync(c); return Map(m); }
    /// <inheritdoc /> public async Task DeleteMetadataAsync(Guid productId, string key, CancellationToken c) { await using var db = await dbFactory.CreateDbContextAsync(c); var m = await db.ProductMetadata.SingleOrDefaultAsync(x => x.ProductId == productId && x.Key == key, c); if (m is not null) { db.ProductMetadata.Remove(m); await db.SaveChangesAsync(c); } }

    private static async Task EnsureUniqueProductAsync(CommerceDbContext db, string slug, string? sku, Guid? id, CancellationToken c) { if (await db.Products.AnyAsync(x => x.Slug == slug && x.Id != id, c)) throw new ValidationException("The product slug is already in use."); if (sku is not null && await db.Products.AnyAsync(x => x.Sku == sku && x.Id != id, c)) throw new ValidationException("The product SKU is already in use."); if (sku is not null && await db.ProductVariants.AnyAsync(x => x.Sku == sku, c)) throw new ValidationException("The SKU is already in use by a variant."); }
    private static async Task ValidateParentAsync(CommerceDbContext db, Guid? parentId, Guid? currentId, CancellationToken c) { if (!parentId.HasValue) return; if (currentId == parentId) throw new ValidationException("A category cannot be its own parent."); var parent = await db.Categories.SingleOrDefaultAsync(x => x.Id == parentId.Value, c) ?? throw new ValidationException("The parent category does not exist."); if (currentId.HasValue) { var seen = new HashSet<Guid> { currentId.Value }; while (parent.ParentId.HasValue) { if (!seen.Add(parent.Id)) throw new ValidationException("The category hierarchy contains a cycle."); if (parent.ParentId == currentId) throw new ValidationException("The category hierarchy cannot contain a cycle."); parent = await db.Categories.SingleOrDefaultAsync(x => x.Id == parent.ParentId.Value, c) ?? break; } } }
    private static void Apply(Product p, UpdateProductCommand c) { p.Name = c.Name.Trim(); p.Slug = c.Slug; p.Sku = c.Sku; p.ShortDescription = c.ShortDescription; p.Description = c.Description; p.Status = c.Status; p.ProductType = c.ProductType; p.Price = c.Price; p.CompareAtPrice = c.CompareAtPrice; p.Currency = c.Currency.ToUpperInvariant(); p.BrandId = c.BrandId; p.UpdatedAt = DateTime.UtcNow; }
    private static ProductModel Map(Product p) => new(p.Id, p.Name, p.Slug, p.Sku, p.ShortDescription, p.Description, p.Status, p.ProductType, p.Price, p.CompareAtPrice, p.Currency, p.BrandId, p.CreatedAt, p.UpdatedAt);
    private static CategoryModel Map(Category x) => new(x.Id, x.Name, x.Slug, x.Description, x.ParentId, x.DisplayOrder);
    private static BrandModel Map(Brand x) => new(x.Id, x.Name, x.Slug, x.Description, x.LogoMediaId);
    private static TagModel Map(Tag x) => new(x.Id, x.Name, x.Slug, x.Description);
    private static ProductVariantModel Map(ProductVariant x) => new(x.Id, x.ProductId, x.Sku, x.Price, x.CompareAtPrice, x.StockQuantity, x.ManageStock, x.Status);
    private static ProductMetadataModel Map(ProductMetadata x) => new(x.Id, x.ProductId, x.Key, x.Type, x.Value);
}
