global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Migrations;
global using MudBlazor;
global using RemoteCommerce.Plugins.Abstractions;
global using System.Security.Cryptography;
global using System.Text;
