namespace RemoteCommerce.Migrations;

/// <summary>Adds the RemoteCommerce catalog persistence schema.</summary>
public partial class ProductCatalog : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("CREATE TABLE [commerce].[Categories] ([Id] uniqueidentifier NOT NULL, [Name] nvarchar(200) NOT NULL, [Slug] nvarchar(200) NOT NULL, [Description] nvarchar(max) NOT NULL, [ParentId] uniqueidentifier NULL, [ImageMediaId] uniqueidentifier NULL, [DisplayOrder] int NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_Categories] PRIMARY KEY ([Id]), CONSTRAINT [FK_Categories_Categories_ParentId] FOREIGN KEY ([ParentId]) REFERENCES [commerce].[Categories] ([Id])); CREATE UNIQUE INDEX [IX_Categories_Slug] ON [commerce].[Categories] ([Slug]); CREATE INDEX [IX_Categories_ParentId] ON [commerce].[Categories] ([ParentId]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[Brands] ([Id] uniqueidentifier NOT NULL, [Name] nvarchar(200) NOT NULL, [Slug] nvarchar(200) NOT NULL, [Description] nvarchar(max) NOT NULL, [LogoMediaId] uniqueidentifier NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_Brands] PRIMARY KEY ([Id])); CREATE UNIQUE INDEX [IX_Brands_Slug] ON [commerce].[Brands] ([Slug]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[Tags] ([Id] uniqueidentifier NOT NULL, [Name] nvarchar(200) NOT NULL, [Slug] nvarchar(200) NOT NULL, [Description] nvarchar(max) NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_Tags] PRIMARY KEY ([Id])); CREATE UNIQUE INDEX [IX_Tags_Slug] ON [commerce].[Tags] ([Slug]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[ProductAttributes] ([Id] uniqueidentifier NOT NULL, [Name] nvarchar(200) NOT NULL, [Slug] nvarchar(200) NOT NULL, [MetadataJson] nvarchar(max) NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_ProductAttributes] PRIMARY KEY ([Id])); CREATE UNIQUE INDEX [IX_ProductAttributes_Slug] ON [commerce].[ProductAttributes] ([Slug]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[Products] ([Id] uniqueidentifier NOT NULL, [Name] nvarchar(200) NOT NULL, [Slug] nvarchar(200) NOT NULL, [Sku] nvarchar(100) NULL, [ShortDescription] nvarchar(max) NOT NULL, [Description] nvarchar(max) NOT NULL, [Status] int NOT NULL, [ProductType] int NOT NULL, [Price] decimal(18,4) NOT NULL, [CompareAtPrice] decimal(18,4) NULL, [Currency] nvarchar(3) NOT NULL, [BrandId] uniqueidentifier NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_Products] PRIMARY KEY ([Id]), CONSTRAINT [FK_Products_Brands_BrandId] FOREIGN KEY ([BrandId]) REFERENCES [commerce].[Brands] ([Id])); CREATE UNIQUE INDEX [IX_Products_Slug] ON [commerce].[Products] ([Slug]); CREATE UNIQUE INDEX [IX_Products_Sku] ON [commerce].[Products] ([Sku]) WHERE [Sku] IS NOT NULL; CREATE INDEX [IX_Products_BrandId] ON [commerce].[Products] ([BrandId]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[ProductAttributeValues] ([Id] uniqueidentifier NOT NULL, [ProductAttributeId] uniqueidentifier NOT NULL, [Value] nvarchar(200) NOT NULL, [Slug] nvarchar(200) NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_ProductAttributeValues] PRIMARY KEY ([Id]), CONSTRAINT [FK_ProductAttributeValues_ProductAttributes_ProductAttributeId] FOREIGN KEY ([ProductAttributeId]) REFERENCES [commerce].[ProductAttributes] ([Id]) ON DELETE CASCADE); CREATE UNIQUE INDEX [IX_ProductAttributeValues_Attribute_Slug] ON [commerce].[ProductAttributeValues] ([ProductAttributeId], [Slug]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[ProductVariants] ([Id] uniqueidentifier NOT NULL, [ProductId] uniqueidentifier NOT NULL, [Sku] nvarchar(100) NOT NULL, [Price] decimal(18,4) NOT NULL, [CompareAtPrice] decimal(18,4) NULL, [StockQuantity] decimal(18,4) NOT NULL, [ManageStock] bit NOT NULL, [Status] int NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_ProductVariants] PRIMARY KEY ([Id]), CONSTRAINT [FK_ProductVariants_Products_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [commerce].[Products] ([Id]) ON DELETE CASCADE); CREATE UNIQUE INDEX [IX_ProductVariants_Sku] ON [commerce].[ProductVariants] ([Sku]); CREATE INDEX [IX_ProductVariants_ProductId] ON [commerce].[ProductVariants] ([ProductId]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[ProductMetadata] ([Id] uniqueidentifier NOT NULL, [ProductId] uniqueidentifier NOT NULL, [Key] nvarchar(200) NOT NULL, [Type] int NOT NULL, [Value] nvarchar(max) NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_ProductMetadata] PRIMARY KEY ([Id]), CONSTRAINT [FK_ProductMetadata_Products_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [commerce].[Products] ([Id]) ON DELETE CASCADE); CREATE UNIQUE INDEX [IX_ProductMetadata_Product_Key] ON [commerce].[ProductMetadata] ([ProductId], [Key]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[ProductMedia] ([Id] uniqueidentifier NOT NULL, [ProductId] uniqueidentifier NOT NULL, [MediaId] uniqueidentifier NOT NULL, [Role] int NOT NULL, [SortOrder] int NOT NULL, [AltText] nvarchar(500) NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_ProductMedia] PRIMARY KEY ([Id]), CONSTRAINT [FK_ProductMedia_Products_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [commerce].[Products] ([Id]) ON DELETE CASCADE); CREATE INDEX [IX_ProductMedia_Product_Sort] ON [commerce].[ProductMedia] ([ProductId], [SortOrder]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[ProductCategories] ([Id] uniqueidentifier NOT NULL, [ProductId] uniqueidentifier NOT NULL, [CategoryId] uniqueidentifier NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_ProductCategories] PRIMARY KEY ([Id]), CONSTRAINT [FK_ProductCategories_Products_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [commerce].[Products] ([Id]) ON DELETE CASCADE, CONSTRAINT [FK_ProductCategories_Categories_CategoryId] FOREIGN KEY ([CategoryId]) REFERENCES [commerce].[Categories] ([Id]) ON DELETE CASCADE); CREATE UNIQUE INDEX [IX_ProductCategories_Product_Category] ON [commerce].[ProductCategories] ([ProductId], [CategoryId]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[ProductTags] ([Id] uniqueidentifier NOT NULL, [ProductId] uniqueidentifier NOT NULL, [TagId] uniqueidentifier NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_ProductTags] PRIMARY KEY ([Id]), CONSTRAINT [FK_ProductTags_Products_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [commerce].[Products] ([Id]) ON DELETE CASCADE, CONSTRAINT [FK_ProductTags_Tags_TagId] FOREIGN KEY ([TagId]) REFERENCES [commerce].[Tags] ([Id]) ON DELETE CASCADE); CREATE UNIQUE INDEX [IX_ProductTags_Product_Tag] ON [commerce].[ProductTags] ([ProductId], [TagId]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[ProductAttributeAssignments] ([Id] uniqueidentifier NOT NULL, [ProductId] uniqueidentifier NOT NULL, [ProductAttributeId] uniqueidentifier NOT NULL, [ProductAttributeValueId] uniqueidentifier NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_ProductAttributeAssignments] PRIMARY KEY ([Id]), CONSTRAINT [FK_ProductAttributeAssignments_Products_ProductId] FOREIGN KEY ([ProductId]) REFERENCES [commerce].[Products] ([Id]) ON DELETE CASCADE, CONSTRAINT [FK_ProductAttributeAssignments_ProductAttributes_ProductAttributeId] FOREIGN KEY ([ProductAttributeId]) REFERENCES [commerce].[ProductAttributes] ([Id]) ON DELETE CASCADE, CONSTRAINT [FK_ProductAttributeAssignments_ProductAttributeValues_ProductAttributeValueId] FOREIGN KEY ([ProductAttributeValueId]) REFERENCES [commerce].[ProductAttributeValues] ([Id]) ON DELETE CASCADE); CREATE UNIQUE INDEX [IX_ProductAttributeAssignments_Unique] ON [commerce].[ProductAttributeAssignments] ([ProductId], [ProductAttributeId], [ProductAttributeValueId]);");
        migrationBuilder.Sql("CREATE TABLE [commerce].[ProductVariantAttributes] ([Id] uniqueidentifier NOT NULL, [ProductVariantId] uniqueidentifier NOT NULL, [ProductAttributeId] uniqueidentifier NOT NULL, [ProductAttributeValueId] uniqueidentifier NOT NULL, [CreatedAt] datetime2 NOT NULL, [UpdatedAt] datetime2 NOT NULL, [IsDisabled] bit NOT NULL, CONSTRAINT [PK_ProductVariantAttributes] PRIMARY KEY ([Id]), CONSTRAINT [FK_ProductVariantAttributes_ProductVariants_ProductVariantId] FOREIGN KEY ([ProductVariantId]) REFERENCES [commerce].[ProductVariants] ([Id]) ON DELETE CASCADE, CONSTRAINT [FK_ProductVariantAttributes_ProductAttributes_ProductAttributeId] FOREIGN KEY ([ProductAttributeId]) REFERENCES [commerce].[ProductAttributes] ([Id]) ON DELETE CASCADE, CONSTRAINT [FK_ProductVariantAttributes_ProductAttributeValues_ProductAttributeValueId] FOREIGN KEY ([ProductAttributeValueId]) REFERENCES [commerce].[ProductAttributeValues] ([Id]) ON DELETE CASCADE); CREATE UNIQUE INDEX [IX_ProductVariantAttributes_Unique] ON [commerce].[ProductVariantAttributes] ([ProductVariantId], [ProductAttributeId], [ProductAttributeValueId]);");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS [commerce].[ProductVariantAttributes]; DROP TABLE IF EXISTS [commerce].[ProductAttributeAssignments]; DROP TABLE IF EXISTS [commerce].[ProductTags]; DROP TABLE IF EXISTS [commerce].[ProductCategories]; DROP TABLE IF EXISTS [commerce].[ProductMedia]; DROP TABLE IF EXISTS [commerce].[ProductMetadata]; DROP TABLE IF EXISTS [commerce].[ProductVariants]; DROP TABLE IF EXISTS [commerce].[ProductAttributeValues]; DROP TABLE IF EXISTS [commerce].[Products]; DROP TABLE IF EXISTS [commerce].[ProductAttributes]; DROP TABLE IF EXISTS [commerce].[Tags]; DROP TABLE IF EXISTS [commerce].[Brands]; DROP TABLE IF EXISTS [commerce].[Categories];");
    }
}
