<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RemoteCommerce.SamplePlugin</AssemblyName>
    <RootNamespace>RemoteCommerce.SamplePlugin</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>RemoteCommerce.SamplePlugin</PackageId>
    <Version>1.0.0</Version> 
    <PackageDescription>Reference plugin used to validate the RemoteCommerce nupkg plugin lifecycle.</PackageDescription>
    <PackageTags>RemoteCommerce;plugin;sample;plugin;rest;</PackageTags>
    <Configuration Condition="'$(Configuration)'==''">Debug</Configuration>
    <Title>SamplePlugin</Title>
    <Authors>Weslley Murdock</Authors>
    <Company>Remote Code Hub</Company>
    <RepositoryUrl>https://github.com/remotecodehub/RemoteCommerce.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://remotecodehub.github.io/RemoteCommerce/</PackageProjectUrl>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../../src/RemoteCommerce.Plugin.Abstractions/RemoteCommerce.Plugin.Abstractions.csproj" />
    <None Include="plugin.manifest.json" Pack="true" PackagePath="" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <None Update="LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
